"strict mode";var p=document.querySelector("body"),q=document.getElementById("ladowanie");document.getElementById("tytul_portalu");document.getElementById("lupka");document.getElementById("wyszukiwarka");document.getElementById("powiad_przycisk");document.getElementById("powiad");document.getElementById("pilne_przycisk");document.getElementById("pilne_wiad");document.getElementById("wiad_przycisk");document.getElementById("wiadomosci");var t=null,v=null;document.getElementById("wiadomosci_tel");document.getElementById("pow_tel");
document.getElementById("wyszukaj");var x=!1,y=!1,z=0;function A(){document.location.reload()}
function B(){var f=document.createElement("nav"),e=document.createElement("div");e.className="menu";var c=document.createElement("header");c.id="tytul_portalu";c.innerHTML="<h1>Pixi</h1>";c.addEventListener("click",A);e.appendChild(c);c=document.createElement("div");c.classList="wyszukaj i";var a=document.createElement("form");a.setAttribute("method","POST");a.className="i";var b=document.createElement("input");b.setAttribute("type","text");b.className="b";b.setAttribute("name","wyszukiwarka");b.id=
"wyszukiwarka";b.setAttribute("placeholder","Szukaj w pixi");b.addEventListener("click",function(){943<=window.innerWidth&&(x?"":document.getElementById("lupka").click())});a.appendChild(b);c.appendChild(a);e.appendChild(c);a=document.createElement("button");a.id="lupka";a.innerHTML="&#128270;";a.addEventListener("click",C);c.appendChild(a);c=document.createElement("div");c.className="telefon";a=document.createElement("button");a.id="wiadomosci_tel";a.className="wiadomosci_ikonka";a.setAttribute("alt",
"wiadomosci");a.innerHTML="&#128232;";b=document.createElement("div");b.className="licznik_menu";b.innerText="488";a.appendChild(b);c.appendChild(a);a=document.createElement("div");a.id="pow_tel";a.style.left="48%";a.className="wiadomosci_ikonka";a.innerHTML="&#128240;";b=document.createElement("div");b.className="licznik_menu";b.innerText="488";a.appendChild(b);c.appendChild(a);a=document.createElement("div");a.appendChild(document.createElement("div"));a.appendChild(document.createElement("div"));
a.appendChild(document.createElement("div"));a.id="hamburger";a.addEventListener("click",function(){document.querySelector(".komputer").classList.toggle("widocznoscz")});c.appendChild(a);e.appendChild(c);c=document.createElement("div");c.className="komputer";a=document.createElement("div");a.className="menu_opcje";b=document.createElement("div");b.innerHTML="X";b.style.background="none";b.style.fontSize="48px";b.style.margin="24px";b.className="zamknij";b.addEventListener("click",function(){document.querySelector(".komputer").classList.toggle("widocznoscz")});
a.appendChild(b);c.appendChild(a);e.appendChild(c);f.appendChild(e);p.appendChild(f);D()}
function E(){var f=document.querySelector(".menu_opcje");[["aktywny_przycisk","Strona g\u0142\u00f3wna"],["powiad_przycisk","Powiadomienia","powiadomienia"],["pilne_przycisk","Pilne wiadomo\u015bci","pilne_wiad"],["wiad_przycisk","Wiadomo\u015bci","wiadomosci"],["dodawanie_posta","Dodaj artyku\u0142"],[" ","M\u00f3j profil"],[" ","Ustawienia"],[" ","Wi\u0119cej"],[" ","Wyloguj"]].forEach(function(e){przycisk=document.createElement("button");przycisk.id=e[0];przycisk.innerText=e[1];3<=e.length&&e[2]&&
(F(przycisk,document.getElementById(e[2]),"#"+e[2]+" h2 button"),licznik=document.createElement("div"),licznik.className="licznik_menu",licznik.innerText="488",przycisk.appendChild(licznik));f.appendChild(przycisk)});document.getElementById("dodawanie_posta").addEventListener("click",G)}
function D(){[["powiadomienia","powiad","Moje powiadomienia","pow_tel"],["pilne_wiad","pilne_wiadom","Pilne wiadomo\u015bci"],["wiadomosci","pilne_wiadom","Wiadomo\u015bci","wiadomosci_tel"],["wyszukaj","wynik_wyszuk","Wyniki wyszukiwania","lupka"]].forEach(function(f){var e=p.appendChild(document.createElement("aside")),c=document.createElement("div");c.id=f[0];c.classList="powiadomienia";var a=document.createElement("h2");"wyszukaj"!=f[0]?a.innerText=f[2]+" :":(a.className="border_none",c.innerHTML=
'\n        <form method="POST" class="i"><input type="text" class="wyszukuwanie" name="wyszukiwarka" id="wyszukiwark" placeholder="Szukaj w pixi"></form>\n        ');var b=document.createElement("button");b.innerText="X";a.appendChild(b);c.appendChild(a);a=document.createElement("div");a.classList="powiad";a.id=f[1];c.appendChild(a);"undefined"!==typeof document.getElementById("lupka")&&c.addEventListener("click",function(){return(!1).j?"":document.getElementById("lupka")});for(b=0;4>b;b++){var d=
document.createElement("div");d.classList="powiadomienie powiad_load";d.innerHTML='<div class="ladowanie_prof"></div>';a.appendChild(d)}e.appendChild(c);4<=f.length&&f[3]&&""!==f[3]&&("lupka"!==f[3]?F(document.getElementById(f[3]),c):F(document.getElementById(f[3]),c,"#wyszukaj h2 button"))});E()}function C(){H()}
function H(){document.getElementById("wiadomosci_tel").classList.toggle("wid");document.getElementById("pow_tel").classList.toggle("wid");document.getElementById("hamburger").classList.toggle("wid")}
function F(f,e,c){f.addEventListener("click",function(){null!=t?t!=e?(v.classList.toggle("aktywny_przycisk"),t.classList.toggle("widocznosc")):"":"";f.classList.toggle("aktywny_przycisk");e.classList.toggle("widocznosc");"wiadomosci_tel"===f.id&&document.getElementById("wiad_przycisk").classList.toggle("aktywny_przycisk");"pow_tel"===f.id&&document.getElementById("powiad_przycisk").classList.toggle("aktywny_przycisk");t!=e?(t=e,v=f):v=t=null});c&&document.querySelector(c).addEventListener("click",
function(){aktywnedymk=!1;f.classList.toggle("aktywny_przycisk");e.classList.toggle("widocznosc");v=t=null;x=!1;e==document.getElementById("wyszukaj")&&H()})}
function G(){function f(g){for(var l=["image/png","image/jpeg","image/gif"],r=0;r<l.length;r++)if(l[r]==g)return!0;return!1}document.getElementById("dodawanie_posta").classList.toggle("aktywny_przycisk");if(y)return document.getElementById("nowa_akcja").style.display="flex",0;var e=p.appendChild(document.createElement("aside")),c=document.createElement("div");c.id="nowa_akcja";var a=document.createElement("div");a.className="nowy_post";var b=document.createElement("div");b.style.borderBottom="1px silver solid";
b.style.padding="4px";b.innerHTML=" &#128196; Utw\u00f3rz nowy artyku\u0142";var d=document.createElement("button");d.className="zamknij";d.innerText="X";d.addEventListener("click",function(){document.getElementById("nowa_akcja").style.display="none";document.getElementById("dodawanie_posta").classList.toggle("aktywny_przycisk")});b.appendChild(d);a.appendChild(b);b=document.createElement("div");b.className="moje_informacje_post";d=document.createElement("div");d.className="ladowanie_prof";d.style.animation=
"powiad_loaduj 2s linear infinite";b.appendChild(d);d=document.createElement("div");d.className="ladowanie_imie_post";b.appendChild(d);d=document.createElement("select");d.id="post_publicznosc";d.setAttribute("name","post_publicznosc");d.title="Czy publiczny?";var h=document.createElement("option");h.value="0";h.innerHTML="&#128219;Prywatny";var m=document.createElement("option");m.value="1";m.innerHTML="&#127759;Publiczny";d.appendChild(m);d.appendChild(h);b.appendChild(d);a.appendChild(b);b=document.createElement("div");
var n=document.createElement("textarea");n.setAttribute("name","post_tresc");n.setAttribute("cols","10");n.setAttribute("rows","4");n.title="Napisz tre\u015b\u0107 posta";n.setAttribute("placeholder","Co s\u0142ycha\u0107?");var k=document.createElement("input");k.setAttribute("type","file");k.setAttribute("name","zdjecia_posta");k.id="zdjecia_posta";k.setAttribute("alt","zdj\u0119cia posta");k.hidden=!0;k.multiple=!0;var w=document.createElement("div");w.id="podglad_zdjec";k.addEventListener("change",
function(){for(var g={g:0};g.g<k.files.length;g={h:g.h,g:g.g,i:g.i},g.g++)g.h=new FileReader,g.h.onload=function(l){return function(){var r=l.h.result,u=document.createElement("img");u.alt="zdj\u0119cie posta";u.src=r;u.dataset.l=k.files[l.g].name+"__nr__"+z;w.appendChild(u)}}(g),f(k.files[g.g].type)?(g.h.readAsDataURL(k.files[g.g]),z++):(alert("Nie dozwolony typ pliku "+k.files[g.g].type),g.i=new FileReader,g.i.readAsDataURL(k.files[g.g]),g.i.addEventListener("load",function(l){return function(){n.value+=
"[nazwa_pliku] "+k.files[l.g].name+" [/nazwa_pliku]\n[tresc_pliku] "+atob(l.i.result.split(",")[1])+" [/tresc_pliku]"}}(g)))});b.appendChild(n);b.appendChild(k);a.appendChild(b);a.appendChild(w);b=document.createElement("div");b.className="dodaj_do_posta";b.innerHTML="<span class='dodaj_do_post'>Dodaj do posta</span>";d=document.createElement("div");d.className="dodaj_do_posta_opcje";h=document.createElement("label");h.setAttribute("for","zdjecia_posta");m=document.createElement("div");m.id="dodaj_zdjecie";
m.title="Dodaj zdj\u0119cie";m.innerHTML="&#128247;";h.appendChild(m);d.appendChild(h);h=document.createElement("div");h.id="dodaj_lokalizacje";h.title="Dodaj lokalizacje";h.innerHTML="&#128506;";d.appendChild(h);h=document.createElement("div");h.id="post_znajomego";h.title="Oznacz znajomego";h.innerHTML="&#128111;";d.appendChild(h);b.appendChild(d);a.appendChild(b);b=document.createElement("div");d=document.createElement("button");d.id="opublikuj";d.innerHTML="Opublikuj";b.appendChild(d);a.appendChild(b);
c.appendChild(a);e.appendChild(c);y=!0}window.onload=function(){B();var f=p.appendChild(document.createElement("main")),e=document.createElement("div");e.className="aktulnosci";f.appendChild(e);p.appendChild(document.createElement("aside")).id="prawa_burta";p.removeChild(q)};