"strict mode";var l=document.querySelector("body"),r=document.getElementById("ladowanie");document.getElementById("tytul_portalu");document.getElementById("lupka");document.getElementById("wyszukiwarka");document.getElementById("powiad_przycisk");document.getElementById("powiad");document.getElementById("pilne_przycisk");document.getElementById("pilne_wiad");document.getElementById("wiad_przycisk");document.getElementById("wiadomosci");var t=null,u=null;document.getElementById("wiadomosci_tel");document.getElementById("pow_tel");
document.getElementById("wyszukaj");var v=!1,y=!1,z=0;
window.onload=function(){B();var f=l.appendChild(document.createElement("main")),d=document.createElement("div");d.className="post";d.style.minHeight="88px";d.style.width="98%";d.style.padding="8px";d.innerHTML='<div class="dodaj_prof" ><img loading="lazy" src="foty/uzytkownik.png" alt="profilowe"></div><div>\n    <div class="co_slychac">Co s\u0142ycha\u0107 Dominiku Kapitan?</div></div>';d.addEventListener("click",C);document.querySelector("main").appendChild(d);d=document.createElement("div");d.id=
"aktulnosci";f.appendChild(d);d=document.createElement("div");D(d);D(d);f.appendChild(d);l.appendChild(document.createElement("aside")).id="prawa_burta";l.removeChild(r);gdzie=document.getElementById("aktulnosci");f=[{idp:"118",iduzytkownika:"2",tresc:"pixel",foty:"",datadodania:"2023-11-26 12:01:14",publiczny:"1",id:"2",imie:"Dominik",nazwisko:"Kapitan",profilowe:"",folder:"dominik_kapitan_2",licznikpolubien:0,licznikomentarzy:0,polubiono:!1,czymoj:!0}];if(0<f.length)for(d=0;d<f.length;d++){var b=
f[d],c=gdzie.appendChild(document.createElement("article")),a=document.createElement("div");a.dataset.J=b.g;a.className="post";c=c.appendChild(a);a=document.createElement("div");a.className="post_informacje";a=c.appendChild(a);var e=document.createElement("a");e.href="/profil/"+b.o;e.style.zIndex=12;a.appendChild(e).appendChild(document.createElement("div")).innerHTML+=""!==b.u&&"uzytkownik.gif"!==b.u?'<img loading="lazy" src="/../foty/'+b.v+"/profilowe/"+b.u+'" alt="profilowe" />':'<img loading="lazy"  src="foty/uzytkownik.png" alt="profilowe" />';
a.innerHTML+='\n                          <a href="/profil/'+b.o+'">    <div class="post_imie">'+b.C+"  "+b.F+' </div></a>\n\n                          <div class="post_data"><a href="/profil/'+b.o+"/post/"+b.g+'"><time>'+b.B+'</time></a><button style="border-radius:8px;margin: 2px 0 0 8px;background:silver;">Doda\u0142/a posta</button></div>\n                          <div class="opcjeposta opcjeposta_usuwanie wysrodkowanie" onclick="menuposta(this)" data-postid="'+b.g+'"><span>...</span></div>';
e=document.createElement("div");e.className="menu_posta_opcje";e.style.display="none";e.dataset.G=b.g;a=a.appendChild(e);!1===b.A?a.innerHTML+="<button>Zg\u0142o\u015b</button>\n                          <button>Zapisz</button>":(""!==b.m&&(a.innerHTML+='<button onclick="zaktalizuj_profilowe('+b.g+')">Zaktalizuj profilowe tym zdjeciem</button>'),a.innerHTML+='<button onclick="usunposta('+b.g+')">Usu\u0144</button>');a=document.createElement("div");a.className="post_tresc";e=b.K.replaceAll("\n","<br>");
a.innerHTML=e;a=c.appendChild(a);""!=b.m&&(post_zdjecia=document.createElement("div"),post_zdjecia.className="post_zdjecia",a.appendChild(post_zdjecia).innerHTML+='<img loading="lazy" src="/foty/'+b.v+"/posty/"+b.m+'" alt="zdjecie posta"/>');dol_posta=document.createElement("div");dol_posta.className="licznik_posta";dol=c.appendChild(dol_posta);2<=b.l?dol.innerHTML+='<div  onclick="pokaz_kto_polubil(this)" class="licznik_polubien" data-postidlicznikpolubien="'+b.g+'"><span>'+b.l+'</span><span class="polubienie"> polubienia</span></div>':
b.l?dol.innerHTML+='<div  onclick="pokaz_kto_polubil(this)" class="licznik_polubien" data-postidlicznikpolubien="'+b.g+'"><span>1</span><span class="polubienie"> polubienie</span></div>':b.l||(dol.innerHTML+='<div  onclick="pokaz_kto_polubil(this)" class="licznik_polubien" data-postidlicznikpolubien="'+b.g+'"><span></span><span class="polubienie"> Brak polubie\u0144</span></div>');dol.innerHTML=b.s?1===b.s?dol.innerHTML+('<div class="licznik_komentarzy" onclick="pokazkomentarze(this)" data-postid="'+
b.g+'"><span data-postid-licznikomentarzyp="'+b.id+'">1</span><span data-postid-licznikomentarzy="'+b.g+'"> komentarz</span></div>'):dol.innerHTML+('<div class="licznik_komentarzy" onclick="pokazkomentarze(this)" data-postid="'+b.g+'"><span data-postid-licznikomentarzyp="'+b.g+'">'+b.s+'</span><span data-postid-licznikomentarzy="'+b.g+'"> komentarze</span></div>'):dol.innerHTML+('<div class="licznik_komentarzy" onclick="pokazkomentarze(this)" data-postid="'+b.g+'"><span data-postid-licznikomentarzyp="'+
b.g+'"></span><span data-postid-licznikomentarzy="'+b.g+'"> Brak komentarzy</span></div>');dol.innerHTML+='<div class="licznik_udustepnien"><span>0</span> udost\u0119pnienia</div>';a=document.createElement("div");a.className="post_akcja srodkowanie";a=c.appendChild(a);a.innerHTML=b.I?a.innerHTML+('<button class="polubione" data-postid="'+b.g+'" onclick="polubposta(this)">polubi\u0142em</button>'):a.innerHTML+('<button data-postid="'+b.g+'" onclick="polubposta(this)">polub</button>');a.innerHTML+=
'<button onclick="pokazkomentarze(this)" data-postid="'+b.g+'">Komentarze</button><button data-postid="'+b.g+'">udust\u0119pnij</button>';a=document.createElement("div");a.className="post_komentarze";c=c.appendChild(a);c.innerHTML+='<div style="margin-left:auto;margin-right:auto;"><div class="dodaj_komentarz_profilowe"><img loading="lazy" src=\'foty/uzytkownik.png\' alt=\'profilowe\' /></div>';c.innerHTML+='\n      <form onsubmit="return false">\n      <input type="text" placeholder="Skomentuj ten wpis" data-postid-kom="'+
b.g+'" />\n      <div style="float:right;">\n      <label>\n          <div data-postid-kom="'+b.g+'" class="dodaj_komentarz" title="wy\u015blij komentarz"><img loading="lazy" src="foty/wyslij.png" alt="dodaj_komentarz"></div>\n          <input data-postid-kom="'+b.g+'" onclick="dodajkomentarza(this)" style="display:none" type="submit" hidden />\n      </label>\n      </div>\n      </form>\n      </div>\n      <div data-postid-pokakom="'+b.g+'" class="komentarze_post wysrodkuj" style="display: none;">\n'}else""!==
document.getElementById("aktulnosci").innerText.trim()?gdzie.innerHTML+="<div class='wszyatkonadzis'>To ju\u017c wszystko na dzi\u015b</div>":document.getElementById("aktulnosci").innerHTML+="<div class='wszyatkonadzis'>Nie ma nic dzisiaj do wy\u015bwietlenia zajrzyj tutaj p\u00f3\u017aniej</div>"};function E(){document.location.reload()}
function B(){var f=document.createElement("nav"),d=document.createElement("div");d.className="menu";var b=document.createElement("header");b.id="tytul_portalu";b.innerHTML="<h1>Pixi</h1>";b.addEventListener("click",E);d.appendChild(b);b=document.createElement("div");b.classList="wyszukaj i";var c=document.createElement("form");c.setAttribute("method","POST");c.className="i";var a=document.createElement("input");a.setAttribute("type","text");a.className="b";a.setAttribute("name","wyszukiwarka");a.id=
"wyszukiwarka";a.setAttribute("placeholder","Szukaj w pixi");a.addEventListener("focus",function(){v||(943<=window.innerWidth&&(v?"":(null!=t&&t!=document.getElementById("wyszukaj")&&(t.classList.toggle("widocznosc"),u.classList.toggle("aktywny_przycisk")),document.getElementById("wyszukaj").classList.toggle("widocznosc"),"wiadomosci_tel"===przycisk.id&&document.getElementById("wiad_przycisk").classList.remove("aktywny_przycisk"),"pow_tel"===przycisk.id&&document.getElementById("powiad_przycisk").classList.remove("aktywny_przycisk"),
t!=document.getElementById("wyszukaj")?(document.getElementById("lupka").classList.toggle("aktywny_przycisk"),t=document.getElementById("wyszukaj"),u=document.getElementById("lupka")):u=t=null,v=!1)),v=!0)});c.appendChild(a);b.appendChild(c);d.appendChild(b);c=document.createElement("button");c.id="lupka";c.innerHTML="&#128270;";b.appendChild(c);b=document.createElement("div");b.className="telefon";c=document.createElement("button");c.id="wiadomosci_tel";c.className="wiadomosci_ikonka";c.setAttribute("alt",
"wiadomosci");c.innerHTML="&#128232;";a=document.createElement("div");a.className="licznik_menu";a.innerText="488";c.appendChild(a);b.appendChild(c);c=document.createElement("div");c.id="pow_tel";c.style.left="48%";c.className="wiadomosci_ikonka";c.innerHTML="&#128240;";a=document.createElement("div");a.className="licznik_menu";a.innerText="488";c.appendChild(a);b.appendChild(c);c=document.createElement("div");c.appendChild(document.createElement("div"));c.appendChild(document.createElement("div"));
c.appendChild(document.createElement("div"));c.id="hamburger";c.addEventListener("click",function(){document.querySelector(".komputer").classList.toggle("widocznoscz")});b.appendChild(c);d.appendChild(b);b=document.createElement("div");b.className="komputer";c=document.createElement("div");c.className="menu_opcje";a=document.createElement("div");a.innerHTML="X";a.style.background="none";a.style.fontSize="48px";a.style.margin="24px";a.className="zamknij";a.addEventListener("click",function(){document.querySelector(".komputer").classList.toggle("widocznoscz")});
c.appendChild(a);b.appendChild(c);d.appendChild(b);f.appendChild(d);l.appendChild(f);F()}
function G(){var f=document.querySelector(".menu_opcje");[["aktywny_przycisk","Strona g\u0142\u00f3wna"],["powiad_przycisk","Powiadomienia","powiadomienia"],["wiad_przycisk","Wiadomo\u015bci","wiadomosci"],["dodawanie_posta","Dodaj artyku\u0142"],[" ","M\u00f3j profil"],[" ","Ustawienia"],[" ","Wi\u0119cej"],[" ","Wyloguj"]].forEach(function(d){przycisk=document.createElement("button");przycisk.id=d[0];przycisk.innerText=d[1];3<=d.length&&d[2]&&(H(przycisk,document.getElementById(d[2]),"#"+d[2]+" h2 button"),
licznik=document.createElement("div"),licznik.className="licznik_menu",licznik.innerText="488",przycisk.appendChild(licznik));f.appendChild(przycisk)});document.getElementById("dodawanie_posta").addEventListener("click",C)}
function F(){[["powiadomienia","powiad","Moje powiadomienia","pow_tel"],["wiadomosci","pilne_wiadom","Wiadomo\u015bci","wiadomosci_tel"],["wyszukaj","wynik_wyszuk","Wyniki wyszukiwania","lupka"]].forEach(function(f){var d=l.appendChild(document.createElement("aside")),b=document.createElement("div");b.id=f[0];b.classList="powiadomienia";var c=document.createElement("h2");"wyszukaj"!=f[0]?c.innerText=f[2]+" :":(c.className="border_none",b.innerHTML='\n        <form method="POST" class="i"><input type="text" class="wyszukuwanie" name="wyszukiwarka" id="wyszukiwark" placeholder="Szukaj w pixi"></form>\n        ');
var a=document.createElement("button");a.innerText="X";c.appendChild(a);b.appendChild(c);c=document.createElement("div");c.classList="powiad";c.id=f[1];b.appendChild(c);for(a=0;4>a;a++){var e=document.createElement("div");e.classList="powiadomienie powiad_load";e.innerHTML='<div class="ladowanie_prof"></div>';c.appendChild(e)}d.appendChild(b);4<=f.length&&f[3]&&""!==f[3]&&("lupka"!==f[3]?H(document.getElementById(f[3]),b):H(document.getElementById(f[3]),b,"#wyszukaj h2 button"))});G()}
function H(f,d,b){f&&f.addEventListener("click",function(){null!=t?t!=d?(u.classList.toggle("aktywny_przycisk"),t.classList.toggle("widocznosc")):"":"";f.classList.toggle("aktywny_przycisk");d.classList.toggle("widocznosc");"wiadomosci_tel"===f.id&&document.getElementById("wiad_przycisk").classList.toggle("aktywny_przycisk");"pow_tel"===f.id&&document.getElementById("powiad_przycisk").classList.toggle("aktywny_przycisk");t!=d?(t=d,u=f):u=t=null;v=!1});b&&document.querySelector(b).addEventListener("click",
function(){aktywnedymk=!1;f.classList.toggle("aktywny_przycisk");d.classList.toggle("widocznosc");u=t=null;v=!1;d==document.getElementById("wyszukaj")&&(document.getElementById("wiadomosci_tel").classList.toggle("wid"),document.getElementById("pow_tel").classList.toggle("wid"),document.getElementById("hamburger").classList.toggle("wid"))})}var I=new Map;
function C(){function f(g){for(var m=["image/png","image/jpeg","image/gif"],w=0;w<m.length;w++)if(m[w]==g)return!0;return!1}document.getElementById("dodawanie_posta").classList.toggle("aktywny_przycisk");if(y)return document.getElementById("nowa_akcja").style.display="flex",0;var d=l.appendChild(document.createElement("aside")),b=document.createElement("div");b.id="nowa_akcja";var c=document.createElement("div");c.className="nowy_post";var a=document.createElement("div");a.style.borderBottom="1px silver solid";
a.style.padding="4px";a.innerHTML=" &#128196; Utw\u00f3rz nowy artyku\u0142";var e=document.createElement("button");e.className="zamknij";e.innerText="X";e.addEventListener("click",function(){document.getElementById("nowa_akcja").style.display="none";document.getElementById("dodawanie_posta").classList.toggle("aktywny_przycisk")});a.appendChild(e);c.appendChild(a);a=document.createElement("div");a.className="moje_informacje_post";e=document.createElement("div");e.className="ladowanie_prof";e.style.animation=
"powiad_loaduj 2s linear infinite";a.appendChild(e);e=document.createElement("div");e.className="ladowanie_imie_post";a.appendChild(e);e=document.createElement("select");e.id="post_publicznosc";e.setAttribute("name","post_publicznosc");e.title="Czy publiczny?";var k=document.createElement("option");k.value="0";k.innerHTML="&#128219;Prywatny";var n=document.createElement("option");n.value="1";n.innerHTML="&#127759;Publiczny";e.appendChild(n);e.appendChild(k);a.appendChild(e);c.appendChild(a);a=document.createElement("div");
var p=document.createElement("textarea");p.setAttribute("name","post_tresc");p.setAttribute("cols","10");p.setAttribute("rows","4");p.title="Napisz tre\u015b\u0107 posta";p.setAttribute("placeholder","Co s\u0142ycha\u0107?");var h=document.createElement("input");h.setAttribute("type","file");h.setAttribute("name","zdjecia_posta");h.id="zdjecia_posta";h.setAttribute("alt","zdj\u0119cia posta");h.hidden=!0;h.multiple=!0;var A=document.createElement("div");A.id="podglad_zdjec";h.addEventListener("change",
function(){for(var g={h:0};g.h<h.files.length;g={h:g.h,i:g.i,j:g.j},g.h++)g.i=new FileReader,g.i.onload=function(m){return function(){I.set(h.files[m.h].name+"__nr__"+z,{H:h.files[m.h]});var w=m.i.result,x=document.createElement("div"),q=document.createElement("div");q.innerText="X";q.className="wyrzuc_fote";q.addEventListener("click",function(){I.has(h.files[m.h].name+"__nr__"+z)?(I["delete"](h.files[m.h].name+"__nr__"+z),x.remove()):alert("Wyst\u0105pi\u0142 b\u0142\u0105d")});x.appendChild(q);
q=document.createElement("img");q.alt="zdj\u0119cie posta";q.src=w;x.dataset.D=h.files[m.h].name+"__nr__"+z;x.appendChild(q);A.appendChild(x)}}(g),f(h.files[g.h].type)?(g.i.readAsDataURL(h.files[g.h]),z++):(alert("Nie dozwolony typ pliku "+h.files[g.h].type),g.j=new FileReader,g.j.readAsDataURL(h.files[g.h]),g.j.addEventListener("load",function(m){return function(){p.value+="[nazwa_pliku] "+h.files[m.h].name+" [/nazwa_pliku]\n[tresc_pliku] "+atob(m.j.result.split(",")[1])+" [/tresc_pliku]"}}(g)))});
a.appendChild(p);a.appendChild(h);c.appendChild(a);c.appendChild(A);a=document.createElement("div");a.className="dodaj_do_posta";a.innerHTML="<span class='dodaj_do_post'>Dodaj do posta</span>";e=document.createElement("div");e.className="dodaj_do_posta_opcje";k=document.createElement("label");k.setAttribute("for","zdjecia_posta");n=document.createElement("div");n.id="dodaj_zdjecie";n.title="Dodaj zdj\u0119cie";n.innerHTML="&#128247;";k.appendChild(n);e.appendChild(k);k=document.createElement("div");
k.id="dodaj_lokalizacje";k.title="Dodaj lokalizacje";k.innerHTML="&#128506;";e.appendChild(k);k=document.createElement("div");k.id="post_znajomego";k.title="Oznacz znajomego";k.innerHTML="&#128111;";e.appendChild(k);a.appendChild(e);c.appendChild(a);a=document.createElement("div");e=document.createElement("button");e.id="opublikuj";e.innerHTML="Opublikuj";a.appendChild(e);c.appendChild(a);b.appendChild(c);d.appendChild(b);y=!0}
function D(f){f.innerHTML+='\n    <article>\n        <div class="post">\n        <div class="post_informacje"><div style="width:58px;height:58px;border:1px solid black;border-radius:50%;background:black;animation:miganie 4s infinite;float:left"></div><div class="post_imie" style="background:black;width:50%;height:48px;left:12%;top:4px;animation:miganie 2s infinite;"></div></div>\n        <div class="post_tresc" style="background:black;height:48px;;animation:miganie 2s infinite;"></div>\n        </div>\n    </article>\n    '};